/* eslint-disable quote-props */
export default {
	name: 'Castle Albarix',
	map: [
		'.....................',
		'.XXXXXXXXXXXXXXXXXXX.',
		'.Xwww-----------wwwX.',
		'.Xwww----XXX----wwwX.',
		'.Xww-----(K)-----wwX.',
		'.Xw---------------wX.',
		'.X-----------------X.',
		'.X-S-------------S-X.',
		'.XXXXXXXXX-XXXXXXXXX.',
		'.^F.....F---F.....F^.',
		'.^F......---......F^.',
		'.XXXUXXXX---XXXXUXXX.',
		'.X------X---X------X.',
		'.X------X---X------X.',
		'.X---G--X---XXXXUXXX.',
		'.^------U----------^.',
		'.X------X----------X.',
		'.XXXXUXXX---XXXXXXUX.',
		'.X------X---X----X-X.',
		'.X------X---X----X-X.',
		'.X------X---X----U-X.',
		'.X------X---XXXXXX-X.',
		'.XXXXXXXX---X----X-X.',
		'.X------U---X----U-X.',
		'.X------X---X----X-X.',
		'.X-XXXX-X---XXXXXXUX.',
		'.X-G----X---X------X.',
		'.X------X---X------X.',
		'.XXXXUXXX---XXXXXXUX.',
		'.X------X---X--G---X.',
		'.X-->---X---X------X.',
		'.XXXXXX^XUUUX^XXXXXX.',
		'..ff..:::::::::..ff..',
		'......:.wwwww.:......',
		'......:.wwwww.:......',
		'.XXXX.:.wwwww.:.XXXX.',
		'.X--S::.......::S--X.',
		'.XX^X.:::---:::.X^XX.',
		'.....................',
	],
	legend: {
		'.': ['grass'],
		':': ['dirt'],
		'-': ['floor'],
		'w': ['water'],
		'U': ['door'],
		'X': ['wall'],
		'^': ['window'],
		'f': ['forest'],
		'F': ['forest'],
		'S': ['floor', 'sentry'],
		'G': ['floor', 'guard'],
		'K': ['floor', 'king'],
		'(': ['signLeft'],
		')': ['signRight'],
		'>': ['floor', { type: 'ladderDown', klimb: 'down' }],
	},
	overflow: 'grass',
	entrance: ['center', 'bottom'],
	exits: {
		edges: ['overworld', 12, 4],
		down: ['castle1B', -1, -1],
	},
};
