/* eslint-disable quote-props */
export default {
	name: 'Castle Albarix',
	map: [
		'.....................',
		'.XXXXXXXXXXXXXXXXXXX.',
		'.Xwww-----------wwwX.',
		'.Xwww----XXX----wwwX.',
		'.Xww-----(K)-----wwX.',
		'.Xw---------------wX.',
		'.X-----------------X.',
		'.X-S-------------S-X.',
		'.XXXXXXXXX-XXXXXXXXX.',
		'.XF.....F---F.....FX.',
		'.XF......---......FX.',
		'.XXXUXXXX---XXXXUXXX.',
		'.X------X---X------X.',
		'.X------X---X------X.',
		'.X------X---XXXXUXXX.',
		'.X------U----------X.',
		'.X------X----------X.',
		'.XXXXUXXX---XXXXXXUX.',
		'.X------X---X----X-X.',
		'.X------X---X----X-X.',
		'.X------X---X----U-X.',
		'.X------X---XXXXXX-X.',
		'.XXXXXXXX---X----X-X.',
		'.X------U---X----U-X.',
		'.X------X---X----X-X.',
		'.X-XXXX-X---XXXXXXUX.',
		'.X-S----X---X------X.',
		'.X------X---X------X.',
		'.XXXXUXXX---XXXXXXUX.',
		'.X------X---X--S---X.',
		'.X-->---X---X------X.',
		'.XXXXXXXXUUUXXXXXXXX.',
		'..ff.............ff..',
		'........wwwww........',
		'........wwwww........',
		'.XXXX...wwwww...XXXX.',
		'.X..S...........S..X.',
		'.XXXX....---....XXXX.',
		'.....................',
	],
	legend: {
		'.': ['grass'],
		'-': ['floor'],
		'w': ['water'],
		'U': ['door'],
		'X': ['wall'],
		'f': ['forest'],
		'F': ['forest'],
		'S': ['floor', 'guard'],
		'K': ['floor', 'king'],
		'(': ['signLeft'],
		')': ['signRight'],
		'>': ['floor', { type: 'ladderDown', klimb: 'down' }],
	},
	overflow: 'grass',
	entrance: ['center', 'bottom'],
	exits: {
		edges: ['overworld', 12, 4],
		down: ['castle1B', -1, -1],
	},
};
