/* eslint-disable quote-props */
export default {
	name: 'Castle Albarix Cellar',
	map: [
		'XXXXXXXXXXXXXXXXXXX',
		'XwwX-----------XwwX',
		'XwwX----XXX----XwwX',
		'XwwX-----------XwwX',
		'XXXX-----------XXXX',
		'X-----------------X',
		'X-----------------X',
		'XXXXXXXXXUXXXXXXXXX',
		'X.......---.......X',
		'X.......---.......X',
		'XXXUXXXX---XXXXXXXX',
		'X------X---U------X',
		'X------X---X------X',
		'X------X---XXXXXXXX',
		'X------U---X------X',
		'X------X---U------X',
		'XXXXXXXX---XXXXXXXX',
		'X......X---X------X',
		'X......U---U------X',
		'X......X---X------X',
		'X......X---XXXXXXXX',
		'XXXXXXXX---X------X',
		'X------U---U------X',
		'X------X---X------X',
		'X------XXXXXXXUXXXX',
		'X------X----------X',
		'X------X----------X',
		'X-X--X-XXXXXXXXXXUX',
		'X------X------S---X',
		'X--<---X----------X',
		'XXXXXXXXXXXXXXXXXXX',
	],
	legend: {
		'.': ['dirt'],
		'-': ['floor'],
		'w': ['water'],
		'U': ['door'],
		'X': ['wall'],
		'f': ['forest'],
		'F': ['forest'],
		'S': ['floor', 'guard'],
		'K': ['floor', 'king'],
		'(': ['signLeft'],
		')': ['signRight'],
		'<': ['floor', { type: 'ladderUp', klimb: 'up' }],
	},
	entrance: ['center', 'bottom'],
	exits: {
		edges: 'BLOCK',
		up: ['castle1', 1, 1],
	},
};
