/* eslint-disable quote-props */
export default {
	name: 'Lands of Lord Lunic',
	map: [
		'wwww.........www....wwwwwwwwwww',
		'wwww..ff.....fw..f..wwwww',
		'www...#f.....ffffff.wwwww',
		'www..###..K....fffff.wwww',
		'www..###........3fff...',
		'www..##........fffff..',
		'www.####.........ff..',
		'www..##D....2....ff..',
		'wwww..#...........f..',
		'www...#.............wwww.1ww',
		'www........f..wwww..wwwww.fw',
		'www.f#...###f....wwww',
		'www.f##.####ffwwwwwww',
		'wwww##...f##ffffwwwww',
		'wwww#.w..f###fffwwwww',
		'wwwwwwwf.ff#fff#wwwww',
		'www...ff...ff.###.1ww',
		'www.........########.',
		'ww..w........ff.#####',
		'wwwwww........f..w...',
		'wwwwwww.ww.......w..w',
	],
	legend: {
		'.': ['grass'],
		'w': ['water'],
		'#': ['mountain'],
		'f': ['forest'],
		'1': ['grass', 'village'],
		'2': ['grass', 'town'],
		'3': ['grass', { type: 'city', enter: ['castle1'] }],
		'D': ['mountain', 'dungeon'],
		'K': ['grass', { type: 'king' }],
	},
	overflow: 'water',
	exits: {
		edges: 'LOOP',
	},
};
