/* eslint-disable quote-props */
export default {
	name: 'Lands of Lord Lunic',
	map: [
		'w........www....wwwww',
		'w..ff....fw..f..wwwww',
		'...#f....ffffff.wwwww',
		'..###..K...fffff.wwww',
		'..###.......3fff...',
		'..##.......fffff..',
		'.####........ff..',
		'..##D....2...ff..',
		'w..#..........f..',
		'...#......w.....wwww.1ww',
		'..........ww....wwwww.fw',
		'.f##.####fwwwwwww',
		'w#....f##fffwwwww',
		'wwwwf.fffff#wwwww',
		'...ff...f.###.1ww',
		'.w......########.',
		'www..........w...',
		'wwww.ww......w...',
	],
	legend: {
		'.': ['grass'],
		'w': ['water'],
		'#': ['mountain'],
		'f': ['forest'],
		'1': ['grass', 'village'],
		'2': ['grass', 'town'],
		'3': ['grass', { type: 'city', enter: ['castle1'] }],
		'D': ['mountain', 'dungeon'],
		'K': ['grass', { type: 'king', isActor: true }],
	},
	overflow: 'water',
	exits: {
		edges: 'LOOP',
	},
};
